### ISSUE TITLE
when run composer install it show error

### ISSUE THREAD

**Issue by askme-gpt** [keizah7/forum#1]
```php
PS D:\phpStudy\PHPTutorial\WWW\forum_7> composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.4 but your HHVM version does not satisfy that requirement.
```
my php version is php7.3.6,and i know laravel 7 require php ^7.2.5， how to fix this ？i don't want to update php version.

**Comment by keizah7** [comment]
Hello @ShuiPingYang ,

please, follow these steps:
1. clone repository
2. `vagrant up`
3. `vagrant ssh`
4. `cd forum`
5. `php74`
6. `composer install`

**Comment by keizah7** [comment]
Hello @ShuiPingYang,

Project code requires PHP 7.4 to run it, but for dependencies installation your can change `composer.json` file 11 line to
```
"php": "^7.3",
```
and then run
```
composer update
vagrant up
vagrant ssh
php74
```
after that, change `php` version in `composer.json` to previous
```
"php": "^7.4",
```
and finally run
```
composer update
```

**Comment by keizah7** [comment]
@ShuiPingYang, how did it go? I tried these steps with php 7.3 and I got succeed
