### ISSUE TITLE
Please make sure the PHP Redis extension is installed and enabled.

### ISSUE THREAD

**Issue by ghost** [keizah7/forum#2]
hello when i tried to create a user account, i had an exception :

"Please make sure the PHP Redis extension is installed and enabled.", i already installed Redis via composer , please help 

also thank you a lot, i really need this forum for my project

**Comment by keizah7** [comment]
Hello @HaruSK,
where are you hosting project? XAMPP, homestead?

**Comment by ghost** [comment]
XAMPP, i'm not using homestead

**Comment by keizah7** [comment]
Homestead has installed redis by default, it would be [solution](https://laravel.com/docs/master/homestead#installation-and-setup).

How to install Redis XAMPP?
1. Install `Redis` service on the machine https://github.com/microsoftarchive/redis/releases
2. Download PECL extension from https://pecl.php.net/package/redis
3. Find version compatable with your php version (Press `DLL` in `Downloads` section)
4. Download file from DLL List (choose `NTS` or `TS` according to `Thread Safety` settings in `phpinfo()`)
5. Extract `.zip` file and move it to `php_redis.dll` to `C:\xampp\php\ext`
6. Add `extension=php_redis.dll` to `C:\xampp\php.ini` file

**Comment by ghost** [comment]
hi , i tried and it was the same, until i did this : 
https://stackoverflow.com/questions/59227836/php-redis-extension-is-installed-and-enabled-in-laravel-6-version 

thanks a lot !! it works perfectly <3
