### ISSUE TITLE
Thread Search Not working

### ISSUE THREAD

**Issue by badal11** [keizah7/forum#9]
It was working until commit 97-First Class Search Instant Results
It didn't work from 98-First-Class-Search-Forum-Integration

**Comment by keizah7** [comment]
Hello,

what errors did you get?

**Comment by badal11** [comment]
I didn't get any errors. The page goes blank i.e only navbar and the search bar shows. Maybe the VUE component of search is not showing up. The Search functionality was working until the commit of First Class Search Instant Results. It didn't work on the next commit. I haven't changed anything on the code. Everything else was working fine till now.
![image](https://user-images.githubusercontent.com/12234447/107632275-5f99c180-6c8e-11eb-9a8a-3919e18ba952.png)

**Comment by keizah7** [comment]
Check console errors. Also you can show me your repository

**Comment by badal11** [comment]
There are no errors. The problem is after searching for a keyword, the page is blank. My repository is the same as yours.  Nothing different.

**Comment by keizah7** [comment]
I can't help you if you not showing any info. Later, I will test the repository by myself

**Comment by badal11** [comment]
Please if possible check it soon. I would highly appreciate that. I am submitting this as a college project tomorrow. Everything works from this project except the search.

**Comment by keizah7** [comment]
You should search issue now if you need it tommorow. I will take a look in weekend

**Comment by badal11** [comment]
Do you have UML class diagrams and data flow diagrams for this project?
